url: "https://guide.nics.nat.gov.tw"
sass:
  sass_dir: assets/css
  style: :compressed
timezone: Asia/Taipei
collections:
  technology:
    name: "前端技術原則"
    output: true
  visual:
    name: "視覺設計"
    output: true
  components:
    name: "共用元件"
    output: true
i18n:
  langs: 
    "en-US": "English (US)"
    "zh-TW": "正體中文"
    ja: "日本語"
    vi: "Tiếng Việt"
    th: "ไทย"
  maturity:
    new:
      key: 新提案
      desc: 未完成開發、請勿使用。
    alpha:
      key: 封閉測試
      desc: 開發暫時性完成，可使用。可能仍有親和力或其他使用上問題待透過實測發現。
    beta:
      key: 公開測試
      desc: 開發暫時性完成，歡迎使用。具有完整親和力報告。
    production:
      key: 已穩定
      desc: 開發完成、歡迎使用。應無任何親和力或使用上問題。
google_analytics: G-N6NH4PCNQK # your own tracking ID